dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-1GB.SATA.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-1.5GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1295-giraffe-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-3GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-qa-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-saola-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-pelican-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129x) += rtd-1296-pelican-rescue.dtb


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
