obj-$(CONFIG_RTK_THERMAL) += rtk-thermal.o

rtk-thermal-y += sensor.o
rtk-thermal-y += sensor-rtd129x.o

rtk-thermal-$(CONFIG_RTK_THERMAL_EOH) += sensor-eoh.o
obj-$(CONFIG_RTK_THERMAL_CPU_CORE_COOLING) += cpu_core_cooling.o
